quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: senha
    jdbc:
      url: jdbc:postgresql://localhost:5432/customer
  hibernate-orm:
    database:
      generation: drop-and-create
